-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 08, 2024 at 10:55 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `users`
--

-- --------------------------------------------------------

--
-- Table structure for table `tempatwisata`
--

CREATE TABLE `tempatwisata` (
  `Place_Name` varchar(1024) DEFAULT NULL,
  `Description` varchar(2500) DEFAULT NULL,
  `Category` varchar(1024) DEFAULT NULL,
  `City` varchar(1024) DEFAULT NULL,
  `Price` bigint(20) DEFAULT NULL,
  `Rating` double DEFAULT NULL,
  `Time_Minutes` varchar(1024) DEFAULT NULL,
  `Coordinate` varchar(1024) DEFAULT NULL,
  `Lat` double DEFAULT NULL,
  `Long` double DEFAULT NULL,
  `Place_Id` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `tempatwisata`
--

INSERT INTO `tempatwisata` (`Place_Name`, `Description`, `Category`, `City`, `Price`, `Rating`, `Time_Minutes`, `Coordinate`, `Lat`, `Long`, `Place_Id`) VALUES
('Pantai Goa Cemara', 'Pantai Goa Cemara  bahasa Jawa                     translit  Pasisir Guwa Cemara   adalah objek wisata pantai yang terletak di Dusun Patihan  Desa Gadingsari  Kecamatan Sanden  Kabupaten Bantul  Daerah Istimewa Yogyakarta  Pantai ini terletak tepatnya berdampingan dengan Pantai Samas dan Pantai Pandansari  n nPantai ini memiliki pasir berwarna hitam tapi lembut dengan ombak yang cukup besar kerakteristik pantai selatan  Pantai ini merupakan pantai pengembangan baru dimana terdapat banyak pohong Cemara udang rindang membentuk seperti goa  hal ini yang membuat pantai ini dinamai Goa Cemara  Pohon Cemara ini bertujuan untuk melindungi abrasi air laut dan menahan gumuk pasir supaya tidak mengalamai perpindahan akibat tiupan angin', 'Bahari', 'Yogyakarta', 4000, 4.3, NULL, '{\'lat\': -7.999422999999998, \'lng\': 110.248963}', -7.999423, 110.248963, 1),
('Pantai Patihan', 'Pantai ini terletak di daerah Srigading  Sanden dan cukup dekat dengan Pantai Goa Cemara  Tempatnya juga asyik banget buat foto foto  nggak beda jauh dengan Pandasari', 'Bahari', 'Yogyakarta', 5000, 4.1, '45.0', '{\'lat\': -7.997777999999999, \'lng\': 110.2449113}', -7.997778, 110.2449113, 2),
('Pantai Kukup', 'Pantai Kukup adalah salah satu pantai yang memiliki hamparan pasir putih yang terkenal di Kabupaten Gunung Kidul  Yogyakarta  Selain memiliki pemandangan pantai yang cantik  pantai ini juga memberikan keunikan tersendiri  Di pantai ini terdapat pulau Karang yang menjadi daya tarik utama bagi para wisatawan lokal atau mancanegara  Karena di pulau Karang ini para wisatawan dapat menikmati keindahan pantai yang sangat menawan  Pantai cantik ini berada di sebelah timurnya Pantai Baron  kurang lebih berjarak sekitar 1 km  Tepatnya berada di Desa Kemadang  Kecamatan Tanjungsari  Kabupaten Gunung Kidul  Yogyakarta  Pantai Kukup ini masih dalam satu barisan dengan Pantai Baron  Pantai Krakal  Pantai Sundak  Pantai Sepanjang dan pantai pantai lainnya  Jarak dari Kota Jogja ke pantai ini sekitar 40 km sedangkan jarak dari Kota Wonosari sekitar 25 km', 'Bahari', 'Yogyakarta', 10000, 4, NULL, '{\'lat\': -8.133876299999999, \'lng\': 110.5548349}', -8.1338763, 110.5548349, 3),
('Pantai Ngrawe (Mesra)', 'Kabupaten Gunungkidul jadi salah satu wilayah di Yogyakarta dengan koleksi pantai terbanyak  Tak terhitung jumlah pantai yang ada di sepanjang pesisir selatannya  Ada yang tetap alami  ada juga yang sengaja mendapat sentuhan agar lebih apik  Salah satunya adalah Pantai Ngrawe yang terletak di Kemadang  Gunungkidul  Sebagai pantai wisata  pantai yang juga terkenal dengan Pantai Mesra ini populer berkat kekuatan media sosial  Sementara pantai lainnya menawarkan keindahan alami  Pantai Ngrawe justru menyajikan konsep  taman  yang tidak biasa  Tertarik untuk mencoba berwisata di taman pinggir pantai  Pantai ini bisa jadi pilihan yang tepat', 'Bahari', 'Yogyakarta', 10000, 4.5, NULL, '{\'lat\': -8.1333389, \'lng\': 110.5537405}', -8.1333389, 110.5537405, 4),
('Pantai Ngobaran', 'Pantai Ngobaran merupakan salah satu tempat wisata alam yang terletak di gugusan laut pantai selatan tepatnya di Desa Kanigoro  kecamatan Saptosari Kabupaten Gunungkidul Daerah Istimewa Yogyakarta 2 km dari pantai Ngrenehan  nPantai ini sangat indah jika air surut maka tampaklah kolam kolam kecil yang terbentuk dari karang karang yang tertutp oleh alga  rumput laut yang hijau sebagai bahan baku kosmetik  dan terdapat banyak biota laut lainnya yang mungkin terjebak di kolam karang tersebut  Hal inilah yang menopanng kehidupan nelayan darat yakni para nelayan yang tidak memerlukan kapal atau perahu untuk mendapatkan hasil laut cukup beraktivitas dipinggir pantai  Biota laut yang sering di dapat adalah Lobster  landak laut  kerang kerangan  bintang laut dan rumput laut itu sendiri tentunya', 'Bahari', 'Yogyakarta', 5000, 4.6, NULL, '{\'lat\': -8.1184844, \'lng\': 110.5028785}', -8.1184844, 110.5028785, 5),
('Pantai Pulang Sawal', 'Pantai Pulang Sawal yang ada di Kecamatan Tepus bisa dicoba  Wisatawan lebih akrab dengan nama Indrayanti untuk merujuk pantai ini  Tidak hanya pengunjung lokal  wisatawan mancanegara pun terpikat dengan pesonanya', 'Bahari', 'Yogyakarta', 10000, 4.5, NULL, '{\'lat\': -8.1506589, \'lng\': 110.6126311}', -8.1506589, 110.6126311, 6),
('Pantai Baron', 'Pantai Baron adalah salah satu objek wisata berupa pantai yang terletak di Desa Kemadang  Kecamatan Tanjungsari  Kabupaten Gunungkidul  Lokasi Pantai Baron dapat ditempuh 40 km daeri pusat kota Yogyakarta  Asal mula nama Pantai Baron berasal dari nama seorang bangsawan asal Belanda yang bernama Baron Skeber  Bangsawan tersebut pernah mendaratkan kapalnya di pantai selatan tepatnya di pantai yang saat ini terkenal dengan sebutan Pantai Baron  Jalan menuju objek wisata Pantai Baron cukup baik untuk dilalui kendaraan pribadi  sepeda motor dan bus Objek wisata Pantai Baron merupakan pantai yang membentuk cekungan  Seperti pantai lainnya  di Pantai Baron tersedia aneka ikan laut beserta olahannya  Ikan yang biasanya dijual di Pantai Baron adalah udang windu  kakap  bawal putih dan tongkol  Pantai Baron memiliki fasilitas berupa tempat pelelangan ikan  wahana permainan anak anak  perahu bermesin  dan toko cenderamata  Buah sirkaya  pisang tanduk  sirsak  dan berbagai macam cenderamata yang terbuat dari kerang laut  Cenderamata berbahan kerang yang banyak dijual di Pantai Baron adalah bros  tirai kerang  lampu hias  cermin berhias karang  figura  dan aneka karakter hewan yang juga terbuat dari kerang laut Upacara sedekah laut adalah upacara yang masih sering dilakukan oleh masyarakat Gunungkidul  Pantai Baron adalah salah satu tempat untuk menyelenggarakan upacara sedekah laut tersebut  Upacara sedekah laut diselenggarakan setiap tanggal satu Syuro dalam penanggalan Jawa  Upacara sedekah laut dilakukan sebagai ungkapan rasa syukur penduduk setempat atas melimpahnya tangkapan ikan di Pantai Baron  Awalnya  sebagaian besar penduduk di sekitar Pantai Baron bukanlah nelayan melainkan petani yang mengolah kebun  Suatu ketika ada seseorang yang memulai menangkap ikan di pinggiran pantai dan mendapatkan banyak ikan  kemudian banyak penduduk yang mengikuti orang tersebut untuk menangkap ikan  Semakin lama  ikan di pinggir pantai semakin sedikit kemudian penduduk mencoba menangkap ikan ketengah laut menggunakan rakit kayu  Adanya kapal di pantai ini karena suatu ketika terjadi tragedi nelayan yang saat menangkap ikan di tengah laut digigit oleh ikan hiu maka kabar ini pun tersiar di mana mana dan menjadikan pemerintah menyumbangkan perahu untuk nelayan Pantai Baron Keunikan Pantai Baron adalah adanya sunga bawah tanah yang mengalir cukup deras ke arah lautan  Sungai bawah tanah tersebut mengalir ke arah laut dan membentuk sebuah sungai  Uniknya sungai bawah tanah yang ada', 'Bahari', 'Yogyakarta', 10000, 4.4, NULL, '{\'lat\': -8.1288246, \'lng\': 110.5487763}', -8.1288246, 110.5487763, 7),
('Pantai Pok Tunggal', 'Pantai Pok Tunggal atau biasa disebut  the hidden paradise   surga yang tersembunyi  adalah salah satu objek wisata yang ada di Yogyakarta tepatnya di Desa Tepus  Tepus  Gunung Kidul  Yogyakarta  Jika dihitung dari kota  maka jarak tempuhnya sejauh 80 km atau sekitar 2 jam perjalanan  nNama Pantai Pok Tunggal diambil karena dipantai tersebut terdapat sebuah pohon duras tua yang berdiri kokoh hingga saat ini  Pantai ini dikelilingi oleh tebing perbukitan karst  Terdapat tebing tebing karang yang ditumbuhi oleh pepohonan yang lebat dan didalamnya dihuni oleh kera kera yang jinak  Uniknya  pantai ini memiliki aliran sungai air tawar dibawah tanah yang menjadi sumber kehidupan bagi masyarakat sekitar pantai  Layaknya pantai selatan lainnya  Pantai Pok Tunggal memiliki pasir putih yang halus dan membentang sepanjang pantai  Sampai saat ini Pantai Pok Tunggal masih terjaga kebersihan dan kealamiannya  nPantai ini sangat ramai dikunjungi baik saat liburan maupun saat hari biasa  Terdapat banyak sekali aktivitas aktivitas yang ditawarkan di Pantai Pok Tunggal  seperti diving  snorkeling  berenang  berkemah  berfoto di spot spot foto yang indah  hingga aktivitas ekstrem seperti rock climbing', 'Bahari', 'Yogyakarta', 10000, 4.5, NULL, '{\'lat\': -8.1554468, \'lng\': 110.6217582}', -8.1554468, 110.6217582, 8),
('Pantai Timang', 'Pantai Timang adalah objek wisata berupa pantai yaitu wilayah yang menjadi batas antara lautan dan daratan yang terletak di Kabupaten Gunungkidul  Daerah Istimewa Yogyakarta  Pantai Timang merupakan salah satu pantai di yogyakarta yang pasirnya berwarna putih  Pantai Timang terletak di antara Pantai Siung dan Pantai Sundak Gunungkidul  Aksesn menuju pantai ini cukup sulit  jalan ke arah pantai ini masih banyak yang belum diaspal karena lokasi pantai ini cukup terpencil  Keunikan pantai ini ialah terdapat sebuah pulau yang menjadi habitat lobster laut diseberang pantai', 'Bahari', 'Yogyakarta', 10000, 4.7, '90.0', '{\'lat\': -8.1759266, \'lng\': 110.6624196}', -8.1759266, 110.6624196, 9),
('Pantai Indrayanti', 'Pantai Indrayanti menawarkan keindahan alam yang menakjubkan  Hamparan pasir dan birunya laut menjadi pesona yang tiada dua  Pantai Indrayanti merupakan salah satu tempat wisata Yogyakarta yang menjadi rekomendasi bagi wisatawan  Jika kamu merasa jenuh di Malioboro  pantai ini bisa menjadi pilihannya', 'Bahari', 'Yogyakarta', 10000, 4.5, NULL, '{\'lat\': -8.1508415, \'lng\': 110.6129852}', -8.1508415, 110.6129852, 10),
('Pantai Nglambor', 'Pantai Nglambor adalah sebuah pantai eksotis yang terletak di Kelurahan Purwodadi  Kecamatan Tepus  Gunung Kidul  Daerah Istimewa Yogyakarta  Lokasinya persis di sebelah barat dari Pantai Siung dan sebelah timur dari Pantai Jogan  Jaraknya kurang lebih 74 km dari pusat kota Jogja  pantai ini menawarkan panorama pantai yang indah  Terdapat dua batu karang besar yang menyerupai kura kura persis di depan teluknya  nAir lautnya yang jernih menjadikan pengunjung bisa dengan leluasa melihat karang  rumput laut  ikan dengan berbagai warna berkejaran  dan aneka biota laut lainnya dari permukaan air  Para pengunjung pun bisa melakukan snorkeling dan berenang di pantai ini tanpa harus khawatir tergulung ombak besar karena memang lokasinya pantainya yang berada di teluk Seringkali pengunjung berasal dari luar kota bahkan luar negeri  seperti turis dari Belanda  Prancis dan Singapura', 'Bahari', 'Yogyakarta', 10000, 4.4, NULL, '{\'lat\': -8.1827028, \'lng\': 110.6792399}', -8.1827028, 110.6792399, 11),
('Pantai Parangtritis', 'Pantai Parangtritis  bahasa Jawa                     translit  Pasisir Parangtritis  adalah tempat wisata yang terletak di Desa Parangtritis  Kretek  Kabupaten Bantul  Daerah Istimewa Yogyakarta  Jaraknya kurang lebih 27 km dari pusat Kota Yogyakarta  Pantai ini boleh terbilang adalah salah satu destinasi wisata terkenal di Yogyakarta dan paling favorit diantara para wisatawan sejak lama  bahkan Pantai Parangtritis telah menjadi ikon pariwisata di Yogyakarta  Pantai Parangtritis mempunyai nilai simbolis yang merupakan garis yang bersifat magis yang menghubungkan Panggung Krapyak  Keraton Yogyakarta  Tugu Yogyakarta dan Gunung Merapi yang dikenal sebagai Garis Imajiner Yogyakarta  nPantai yang terletak di sisi timur Pantai Parangkusumo ini terkenal diantara para wisatawan karena memiliki legenda yang melekat dengan Ratu Kidul sebagai penguasa laut selatan dan keindahannya  Pantai ini merupakan pantai yang cukup luas di Yogyakarta  berbeda dengan pantai pantai di kawasan Yogyakarta lainya seperti Pantai di Gunungkidul yang ukurannya relatif kecil', 'Bahari', 'Yogyakarta', 10000, 4.5, NULL, '{\'lat\': -8.024607999999999, \'lng\': 110.3298045}', -8.024608, 110.3298045, 12),
('Pantai Depok Jogja', 'Pantai Depok  bahasa Jawa                  translit  Pasisir Dh pok  merupakan objek wisata pantai yang terletak di Kecamatan Kretek  Kabupaten Bantul  Daerah Istimewa Yogyakarta  sekitar tiga puluh kilometer di sebelah selatan Kota Yogyakarta  Pantai ini terkenal akan pasar ikannya yang ikannya merupakan hasil tangkapan nelayan Pantai Depok', 'Bahari', 'Yogyakarta', 10000, 4.3, NULL, '{\'lat\': -8.0137087, \'lng\': 110.2914777}', -8.0137087, 110.2914777, 13),
('Pantai Sundak', 'Pantai Sundak merupakan salah satu pantai indah yang berada di Gunung Kidul tepatnya di dekat Pantai Indrayanti  Pantai ini berpasir putih dan memilii air yang masih bersih  bening  dan menyegarkan  Tetapi ombak di Pantai Sundak ini sangat besar  jadi jika anda ingin bermain air di Pantai Sundak diharapkan untuk berhati hati  Selain bermain air anda juga bisa berjalan jalan di tepi pantai sambil menikmati keindahan pantai ini  Jika anda berjalan di tepi pantai sampai sejauh 40 meter anda akan menemukan batu batu karang kecil berjajar dan batu batu karang tersebut adalah tempat persembunyian hewan hewan laut yang kecil  tetapi harus tetap berhati hati karena batu karang tersebut begitu tajam', 'Bahari', 'Yogyakarta', 5000, 4.5, NULL, '{\'lat\': -8.147072, \'lng\': 110.6079043}', -8.147072, 110.6079043, 14),
('Pantai Sepanjang', 'Siapa sangka  ternyata Yogyakarta pun punya  Kuta  nya sendiri Ialah Pantai Sepanjang  salah satu pantai di Kabuaten Gunungkidul  Daerah yang satu ini memang memiliki koleksi pantai cantik yang tak terhitung jumlahnya  Bahkan pantai ini digadang gadang sebagai  Kuta Tempo Doeloe   Memang  pesona seperti apa yang ditawarkan pantai ini', 'Bahari', 'Yogyakarta', 10000, 4.4, '120.0', '{\'lat\': -8.136665599999999, \'lng\': 110.5659962}', -8.1366656, 110.5659962, 15),
('Pantai Krakal', 'Pantai krakal merupakan pantai strategis untuk singgah  selain bisa menikmati panorama laut  wisatawan juga bisa mencicipi kuliner laut  Terdapat icon berupa bangunan berbentuk ikan diatas bukit yang sering dijadikan tempat foto', 'Bahari', 'Yogyakarta', 10000, 4.5, NULL, '{\'lat\': -8.145019, \'lng\': 110.5998857}', -8.145019, 110.5998857, 16),
('Pantai Glagah', 'Pantai Glagah Indah adalah salah satu pantai yang menjadi objek wisata di provinsi Daerah Istimewa Yogyakarta  Pantai Glagah Indah merupakan salah satu pantai di Yogyakarta dengan hamparan pasir yang berwarna hitam dan banyak mengandung pasir besi  Pantai Glagah Indah memiliki akses yang baik', 'Bahari', 'Yogyakarta', 5000, 4.4, NULL, '{\'lat\': -7.911942699999999, \'lng\': 110.0647339}', -7.9119427, 110.0647339, 17),
('Pantai Siung', 'Pantai Siung adalah suatu objek wisata pantai yang terletak di Kec  Tepus  tepatnya berada di Dusun Duwet  Kelurahan Purwodadi  Kecamatan Tepus  Kabupaten Gunungkidul  provinsi Daerah Istimewa Yogyakarta  Lokasinya berjarak kurang lebih 75 km dari kota Yogya dan memiliki jalur panjat tebing dengan 250 jalur berstandar internasional  nDi sepanjang perjalanan menuju lokasi pantai  Anda akan disuguhi pemandangan bukit kapur yang ditumbuhi pohon pohon jati  Jalan yang berkelok kelok dan menaik  merupakan tantangan yang harus Anda lewati sebelum mencapai Pantai Siung  Akan tetapi  perjalanan yang melelahkan akan terbayar ketika Anda sudah berada di kawasan Pantai Siung  Pantai dengan hamparan pasir putih dan suara deburan ombak  akan membuat suasana hati dan pikiran Anda tenang dan damai  nKarena pantai ini sangat terpencil  fasilitas yang tersedia masih minim  Untuk akomodasi penginapan belum tersedia di sini  tetapi jika Anda ingin bermalam di Pantai Siung  Anda bisa menggunakan pondok pemanjat yang bentuknya mirip rumah panggung dengan kapasitas kurang lebih sekitar 20 orang  Jika Anda ingin bermalam dengan suasana alam  anda bisa membawa tenda sendiri yang bisa Anda gunakan di area camping ground  nJika Anda dari Kota Yogyakarta  Anda bisa menggunakan jalur Yogyakarta Wonosari Tepus Purwodadi Pantai Siung  Jika Anda menggunakan transportasi umum  Anda dapat menggunakan bus dari Terminal Giwangan Yogyakarta dengan menggunakan bus jurusan Jogja Wonosari  Sampai di terminal Wonosari  Anda dapat menggunakan angkutan umum jurusan Wonosari Jepitu  Sesampai Pertigaan Balai Desa Purwodadi  Anda bisa menggunakan jasa ojek  karena hanya itu transportasi umum yang bisa digunakan sampai ke Pantai Siung', 'Bahari', 'Yogyakarta', 10000, 4.6, NULL, '{\'lat\': -8.1818233, \'lng\': 110.6832394}', -8.1818233, 110.6832394, 18),
('Pantai Sadranan', 'Pantai Sadranan Jogja adalah butiran intan permata tersembunyi yang tiba tiba memunculkan diri  dari dalam tumpukan harta karun deretan pantai pantai indah di Jogja  Seperti halnya pantai pantai lain di kawasan Selatan Jogja  Pantai Sadranan juga memiliki ciri khas pasir putih dengan karang koral di area sangaet dekat dengan bibir pantai  Pasir putih ini mengingatkan pada Pantai terkenal semacam Kuta di Bali dan Mandalika di Lombok  Namun pantai di gunung kidul ini punya kelebihan dari 2 pantai terkenal itu  yaitu terdapatnya koral karang di pantai  Selain itu  pantai ini juga masih terbilang sepi  Kedua kelebihan ini  membuat pengunjung benar benar bisa menikmati keasrian pantai tanpa harus terganggu hiruk pikuknya manusia', 'Bahari', 'Yogyakarta', 10000, 4.6, NULL, '{\'lat\': -8.145667999999997, \'lng\': 110.6043914}', -8.145668, 110.6043914, 19),
('Pantai Nguluran', 'Di pantai Nguluran anda hanya bisa melihat hamparan laut luas serta spot foto  Semua fasilitas itu adanya di atas tebing  Sekitar belasan meter dari permukaan air pantai  Spot favorit di resort pantai ini adalah teras kaca  Teras kaca ini dapat dijadikan spot selfie dengan latar belakang pantai  Pengunjung akan mendapatkan foto yang sangat bagus dan indah untuk dipajang di IG  FB  atau media sosial lain  Apalagi jika foto diambil saat sunset  Saat berfoto di teras kaca  pengunjung akan merasakan sensasi yang menegangkan  Sensasi tegang ini timbul akibat teras kaca yang tepat berdiri di atas pinggir laut  Sensasi yang timbul seperti berjalan di atas seutas tali pada ketingian belasan meter di atas air laut  Namun tidak perlu kuatir  pihak pengelola menjamin keselematan para pengunjung  sepanjang tidak melanggar peraturan yang sudah di buat pihak pengelola', 'Bahari', 'Yogyakarta', 10000, 4.1, NULL, '{\'lat\': -8.1060061, \'lng\': 110.4618655}', -8.1060061, 110.4618655, 20),
('Pantai Samas', 'Pantai Samas  bahasa Jawa               translit  Pasisir Samas  merupakan salah satu pantai yang berada di deretan pantai sebelah timur Pantai Parangtritis  Lokasi Pantai Samas kurang lebih 14 km arah selatan Kota Bantul atau sekitar 35 km dari pusat Kota Yogyakarta  tepatnya di Desa Srigading  Kecamatan Sanden  Kabupaten Bantul  Daerah Istimewa Yogyakarta', 'Bahari', 'Yogyakarta', 4000, 4, '45.0', '{\'lat\': -8.0045535, \'lng\': 110.2703756}', -8.0045535, 110.2703756, 21),
('Pantai Drini', 'Pantai Drini adalah salah satu objek wisata yang terletak di Desa Banjarejo  Kecamatan Tanjungsari Gunungkidul  Yogyakarta  Letaknya di sebelah timur Pantai Baron dan berjarak sekitar 1 km ke arah timur Pantai Sepanjang  Namun jarak sebenarnya yang harus ditempuh untuk sampai ke pantai ini sejauh 60 km atau sekitar 2 3 jam dari Kota Yogyakarta  Infrastruktur menuju ke Pantai Drini cukup mulus  walaupun jalan masuk untuk sampai ke pantai ini cukup terjal dan berkelok kelok  Pantai Drini merupakan pantai yang langsung berhadapan dengan Samudra Hindia  Pantai ini memiliki lereng pantai yang cukup curam sekitar 10 derajat dan merupakan bagian dari Wonosari yang didominasi oleh batuan karst dari Gunung Sewu  Pantai ini belum banyak terjamah oleh wisatawan lokal maupun asing  karena letaknya yang berada di daerah terpencil  Sehingga  Pantai Drini ini dikenal dengan nama Pantai Perawan  Sebutan ini digunakan oleh masyarakat setempat karena kondisi Pantai Drini yang masih bersih  udara yang sejuk  air yang terasa dingin ditambah dengan hamparan pasir putih yang mempesona dan aliran airnya yang tidak seganas Pantai Parangtritis Pantai ini memiliki sebuah tebing besar yang berada di tengah tengah pantai dan membagi pantai ini menjadi dua sisi  yaitu sisi barat dan sisi timur   Tebing ini terlihat begitu indah sehingga membuatnya seolah olah seperti pulau kecil yang terapung di tengah pantai  Di atas karang ini dibangun mercusuar dimana dari menaranya mata kita akan dimanjakan dengan pemandangan yang luar biasa indahnya   Di pantai ini pengunjung juga dapat melihat dengan jelas rumput rumput laut di antara karang karang laut dan biota laut lainnya', 'Bahari', 'Yogyakarta', 10000, 4.5, NULL, '{\'lat\': -8.1384509, \'lng\': 110.577522}', -8.1384509, 110.577522, 22),
('Pantai Wediombo', 'Pantai Wediombo  O Jawa  Wedhiamba  adalah sebuah pantai yang berada di Desa Jepitu  Girisubo  Gunungkidul di dekat Pantai Siung  berjarak 80 km dari kota Yogyakarta  Pantai tersebut meliputi sebuah teluk yang dikelilingi pegunungan batu karang dan pasir putih  Di tengah laut  batu karang tampak menonjol  Tempat tersebut juga dipakai untuk selancar  Ketinggian ombak dapat mencapai 3 4 meter  Pantai Wediombo menghadap ke barat dan matahari berada di sisi selatan  pada November Mei   Dari pantai ini  orang orang dapat melihat matahari terbenam pada waktu sore  Selin untuk berselancar  Wediombo juga memiliki kolam alami sampai perairan tanpa ombak  Ada pula tempat untuk snorkeling  Wediombo masuk salah satu dari 13 tempat yang masuk Cagar Alam Dunia UNESCO Gunung Sewu', 'Bahari', 'Yogyakarta', 5000, 4.5, NULL, '{\'lat\': -8.1862462, \'lng\': 110.709901}', -8.1862462, 110.709901, 23),
('Pantai Jogan', 'Pantai Jogan adalah objek wisata pantai yang terletak di Dusun Duwet  Purwodadi  Tepus  Kabupaten Gunungkidul  Daerah Istimewa Yogyakarta  Lokasinya berjarak kurang lebih 74 km dari Pusat kota Yogyakarta  Pantai ini terletak di jajaran pegunungan Gunungkidul  yang memberikan pemandangan alam tebing dan air terjun yang mengarah ke laut lepas', 'Bahari', 'Yogyakarta', 5000, 4.4, NULL, '{\'lat\': -8.180135, \'lng\': 110.6763715}', -8.180135, 110.6763715, 24),
('Pantai Ngrenehan', 'Pantai Ngrenehan merupakan npantai nelayan  Terletak di desa Kanigoro nKecamatan Saptosari kurang lebih 30 km di sebelah selatan kota Wonosari  Suatu pantai berupa teluk yang dikelilingi hamparan perbukitan kapur dan memiliki panorama yang sangat memukau dengan deburan ombak menerpa pasir putih  Para wisatawan dapat menyaksikan aktivitas kegiatan nelayan dan menikmati ikan siap saji atau membawa ikan segar sebagai oleh oleh', 'Bahari', 'Yogyakarta', 3000, 4.4, NULL, '{\'lat\': -8.1211475, \'lng\': 110.5142337}', -8.1211475, 110.5142337, 25),
('Pantai Jungwok', 'Pantai Jungwok adalah pantai yang terletak di Desa Jepitu  Kecamatan Girisubo  Kabupaten Gunungkidul  Daerah Istimewa Yogyakarta  Pantai Jungwok merupakan salah satu pantai yang memiliki panorama yang indah dengan pasir putih yang khas dari pantai di Gunung Kidul  Pantai Jungwok terletak di sebelah Timur Pantai Wediombo dan di sebelah Barat Pantai Ngusalan  Jarak Pantai Jungwok dari Kota Wonosari sekitar 40 km  Akses jalan menuju Pantai Jungwook masih cukup sulit  itu dikarenakan jalan yang masih belum diaspal  Pantai Jungwok sering menjadi destinasi wisata karena tempatnya yang nyaman untuk berkemah', 'Bahari', 'Yogyakarta', 5000, 4.6, NULL, '{\'lat\': -8.197822, \'lng\': 110.7123397}', -8.197822, 110.7123397, 26),
('Pantai Greweng', 'Di Kabupaten Gunungkidul  tidak sulit memilih pantai yang masih sepi dan indah  Pantai Greweng yang berada di Kecamatan Girisubo adalah satu di antaranya  Tidak hanya cantik  pantai ini juga dikenal sebagai destinasi untuk berkemah  Namun  siapkan energi lebih untuk mencapai lokasinya yang terpencil', 'Bahari', 'Yogyakarta', 5000, 4.6, NULL, '{\'lat\': -8.197864399999998, \'lng\': 110.7186216}', -8.1978644, 110.7186216, 27),
('Pantai Sedahan', 'Pantai Sedahan ini memiliki garis pantai yang cukup panjang dan cukup luas untuk dijadikan sebagai arena bermain  Pada kedua sisi pantai  terdapat tebing karang yang mengapit pantai ini dan menjorok ke tengah laut  Pantai Sedahan mempunyai deburan ombak yang khas laut selatan dan hamparan pasir putih dengan butiran butiran yang halus  Air Biru kehijauan yang bening  segar  dan berkilauan teritampa cahaya matahari akan menghipnotis siapa pun untuk bermain air dan menceburkan diri di pantai tersebut  Tetapi pengunjung harus tetap berhati hati karena pantai selatan selalu berarus dan berombak kuat  maka para pengunjung tidak disarankan untuk berenang terlalu jauh dari daratan  Pantai Sedahan ini juga dikenal oleh banyak orang sebagai lokasi memancing yang menyenangkan  Banyak pengunjung yang rela dan menyempatkan datang jauh jauh hanya untuk memancing ikan di Pantai Sedahan ini', 'Bahari', 'Yogyakarta', 5000, 4.5, NULL, '{\'lat\': -8.1978943, \'lng\': 110.7208535}', -8.1978943, 110.7208535, 28),
('Pantai Watu Kodok', 'Pantai Watu Kodok merupakan salah satu pantai yang ada di Gunung Kidul  Pantai Watu Kodok ini memiliki pasir putih dan air laut yang masih berwarna biru yang sangat indah  Di pantai ini terdapat beberapa batu karang yang terjal  batu tersebut menjadi daya tarik para wisatawan dan keunikan bagi pantai itu sendiri  Dan suasana pantai yang masih alami juga menjadikan pantai ini menjadi daya tariknya  tetapi pantai ini masih tergolong pantai baru jadi masih belum banyak wisatawan  Pantai Watu Kodok ini sangat cocok bagi Anda yang ingin menghabiskan waktu liburan bersama keluarga', 'Bahari', 'Yogyakarta', 5000, 4.6, NULL, '{\'lat\': -8.1370556, \'lng\': 110.5746611}', -8.1370556, 110.5746611, 29),
('Pantai Kesirat', 'Pada umumnya pantai identik dengan pasirnya bukan  namun pantai kesirat memiliki keunikan tersendiri yang akan anda temukan disini  Pantai kesirat tidak memiliki pasir namun anda akan menemukan tebing tebing yang memeiliki struktur yang cantik kemudian anda kana menikmati pantai di atasnya  tempat ini juga sangat cocok untuk menikmati sunset  Keindahan pantai ini membuat semua orang tidak bisa melupakannya seperti janji mantan hehee   pantai kesirat memiliki spot spot foto yang instagramable banget cocok sekali untuk kamu yang suka berfoto  Keunikan lain yang menjadi ciri khas dari wisata Pantai Kesirat adalah hadirnya sebuah pohon yang tampak berdiri kokoh yang menjadi ikon dari tempat wisata ini  Banyak wisatawan yang memanfaatkan pohon ini sebagai latar belakang foto mereka', 'Bahari', 'Yogyakarta', 5000, 4.6, '90.0', '{\'lat\': -8.096153500000002, \'lng\': 110.4350483}', -8.0961535, 110.4350483, 30),
('Pantai Ngandong', 'Pantai Ngandong terletak di Desa Sidoarjo  Kecamatan Tepus  Kabupaten Gunung Kidul  Yogyakarta  Pantai ini sebenarnya tidak jauh dari Pantai Indrayanti yang lebih terkenal dahulu  tepatnya terletak di sebelah barat laut dari pantai Indrayanti  Pantai Ngandong termasuk pantai yang kecil namun mempunyai ciri khas tersendiri yang menjadi daya tarik bagi wisatawan  Meskipun demikian belum banyak wisatawan yang mengetahui destinasi wisata pantai ini  Pantai ini ramai penunjung ketika musim liburan  namun sepi ketika hari hari biasa', 'Bahari', 'Yogyakarta', 10000, 4.5, NULL, '{\'lat\': -8.146423, \'lng\': 110.6061408}', -8.146423, 110.6061408, 31),
('Pantai Sanglen', 'Pantai Sanglen  Lokasinya berada di Desa Kemadang  Gunung Kidul  Pantai indah yang satu ini memang terdengar asing di telinga  namun ternyata pantai ini menyimpan keindahan yang sangat menenangkan  Keadaan ombaknya diam diam menghanyutkan membuat kita harus berhati hati jika ingin bermain air ketika sedang pasang  namun ketika surut kamu dapat bemain ombak di sekitar pantainya  Tak jauh dari area pantai terdapat sebuah bukit dengan hiasan pepohonan yang masih rindang serta berwarna hijau alam  kamu dapat naik ke atas bukit melalui tangga yang sudah disediakan', 'Bahari', 'Yogyakarta', 10000, 4.5, NULL, '{\'lat\': -8.1367456, \'lng\': 110.5716362}', -8.1367456, 110.5716362, 32),
('Pantai Congot', 'Selain Pantai Glagah dan Pantai Trisik  ternyata masih ada satu lagi pantai yang berada di Kulon Progo  Yakni Pantai Congot  pantai yang satu ini terkenal sebagai surganya memancing ikan  Maka tak heran jika Pantai Congot banyak dikunjungi oleh mereka para mancing mania  selain itu masyarakat sekitar Pantai Congot menggantungkan hidupnya sebagai nelayan  Pantai Congot memang tak sepopuler pantai lain yang ada di Kulon Progo  mulai banyak dikunjungi wisatawan ketika dibukanya Hutan Mangrove Pasir Mendit  Karena memang lokasinya yang tak terlalu jauh dari Pantai Congot  yakni berada di sebelah barat pantai  Pantai Congot merupakan muara dari Sungai Bogowonto  Ini pulalah yang menyebabkan Pantai Congot menjadi spot favorite para pemancing  karena terdapat banyak jenis ikan yang ada mulai dari ikan air tawar  ikan air payau hingga ikan air asin', 'Bahari', 'Yogyakarta', 3000, 4.3, NULL, '{\'lat\': -7.907542500000001, \'lng\': 110.0535658}', -7.9075425, 110.0535658, 33);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tempatwisata`
--
ALTER TABLE `tempatwisata`
  ADD PRIMARY KEY (`Place_Id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
